FROM py3:latest

SHELL ["/bin/bash", "--login", "-i", "-c"]

#RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash && \
    source /root/.bashrc && \
    nvm install 14 15 16 17 18 19 20

EXPOSE 3000 5000

WORKDIR /app
CMD ["bash"]